#!/bin/bash

# get machine (Linux/Mac/Windows/other) {{{1
uname_output="$(uname -s)"
case "${uname_output}" in
	Linux*)			machine="Linux";;
	Darwin*)		machine="Mac";;
	CYGWIN*|MINGW*)	machine="Windows";;
	*)				machine="UNKNOWN:${uname_output}"
esac

if [[ -d "$1" || -f "$1" ]]; then
  echo "file or directory $1 already exists!"
else
  mkdir "$1"
  mkdir "$1/srcs"
  touch "$1/srcs/main.c"
  mkdir "$1/includes"
  touch "$1/includes/$1.h"
  echo "$USER" > "$1/author"
  git clone https://github.com/cmicheledelaney/libft "$1/libft"
  mv "$1/libft" "$1/srcs/"
  if [[ ! -f Makefile_template ]]; then
    curl https://raw.githubusercontent.com/cmicheledelaney/42project/master/Makefile_template > Makefile_template
  fi
  cp ~/Makefile_template "$1/Makefile"
  if [[ "${machine}" == "Linux" ]]; then
    sed -i "s/PROJECTNAME/$1/g" "$1/Makefile"
  else
    sed -i "" "s/PROJECTNAME/$1/g" "$1/Makefile"
  fi
fi
